### ISSUE TITLE
RPI2 Builds

### ISSUE THREAD

**Issue by jajms** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#24]
Did something break on version 3.3.2?
Version 3.3 works perfectly fine for me (definitely a bit slow, but it's still usable in my opinion), haven't tried building it myself, but I was just wondering if something went wrong with the RPI2 build

**Comment by hiulit** [comment]
If they work, then it's a miracle! Haha! No, jokes aside, the toolchain I use only compiles for the Raspberry Pi versions 3 and 4. so I removed them. You might want to try either one of those and see if they work with the Pi 2 ;)

Also, try updating to the latest versions, or at least >= 3.3.4, because they made internal changes and the editor is much more snappier.
